version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
    depends_on:
    - "noise"
  animal:
    build: ./animal
    image: rwright1992/animal-jenkins-swarm:latest
    ports:
    - target: 5001
      published: 5001
  noise:
    build: ./noise
    image: rwright1992/noise-jenkins-swarm:latest
    ports:
    - target: 5000
      published: 5001
    depends_on:
    - "animal"